development:
  adapter: postgresql
  encoding: unicode
  database: zappos_dev
  pool: 5
  username: postgres
  password: postgres


production:
  adapter: postgresql
  encoding: unicode
  database: zappos_test
  pool: 5
  username: postgres
  password: postgres
